apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: appesports-back
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: appesports-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: appesports-back
        image: akswebsportscr.azurecr.io/appesports-back:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: appesports-back
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: appesports-back

